### ISSUE TITLE
Assembly supporting files .inc is not compatible with GNU assembler

### ISSUE THREAD

**Issue by Nan0416** [DarkSector/AVR#1]
Using the avr-as will generate a list of errors that look like the following,

m328Pdef.inc:963: Error: expected comma after "SPIaddr"
m328Pdef.inc:964: Error: expected comma after "URXCaddr"
m328Pdef.inc:965: Error: expected comma after "UDREaddr"

Do you have a version of these .inc files for the gnu assembler?

**Comment by DarkSector** [comment]
Unfortunately not. The .inc files are included with the Atmel Studio. 

https://www.microchip.com/avr-support/atmel-studio-7

Also, why would GAS support ATMEL archs? You should use avra instead.

**Comment by DarkSector** [comment]
Closing issue on account of inactivity
